### PR TITLE
Plist fixes

### LINKED ISSUE #53: Build phases no longer generate comments where their files are from

### PR DESCRIPTION
**Pull request by yonaskolb**
- moves plist values into their base classes (PBXBuildPhase and PBXTarget)
- fixes #53
- fixes PBXAggregateTarget buildConfigurationList

### CODE REVIEW

File: Sources/PBXAggregateTarget.swift [hunk 1]
```diff
@@ -11,32 +11,6 @@ public class PBXAggregateTarget: PBXTarget {
 extension PBXAggregateTarget: PlistSerializable {
     
     func plistKeyAndValue(proj: PBXProj) -> (key: CommentedString, value: PlistValue) {
-        var dictionary: [CommentedString: PlistValue] = [:]
-        dictionary["isa"] = .string(CommentedString(PBXAggregateTarget.isa))
-        let buildConfigurationListComment = "Build configuration list for PBXAggregateTarget \"\(name)\""
-        dictionary["buildConfigurationList"] = .string(CommentedString(PBXNativeTarget.isa,
```
Comment (yonaskolb) [inline Sources/PBXAggregateTarget.swift]: @pepibumur Let me know if this `PBXNativeTarget.isa` was there for a reason. Looks like it was a bug, and is supposed to be `buildConfigurationList`

Comment (pepibumur) [reply Sources/PBXAggregateTarget.swift]: Yeah, it's definitively a bug. Good catch.
